### ISSUE TITLE
Specs failing

### ISSUE THREAD

**Issue by AbuMareBear** [Freika/opst#2]
I tried to run the specs but I four failures and a pending. Is this the case with your setup or have I missed something?

**Comment by AbuMareBear** [comment]
Okay. The specs were not passing because the seasons created need a finishes_at time. I can submit a PR for this but I was wondering if you could select a license for this project.

**Comment by Freika** [comment]
@imabusabah I selected MIT license.

**Comment by Freika** [comment]
Solved by #5
